<?php

/**
 * Map Laravel route names to permission slugs for route middleware.
 *
 * @var array<string, string>
 */
return [
    'routes' => [
        'dashboard' => 'dashboard.view',
        'job.drafting' => 'dashboard.view',
        'job.drafting-request-form' => 'dashboard.view',
        'job.drafting-request-form.store' => 'dashboard.view',
        'crm.index' => 'dashboard.view',
        'profile.edit' => 'profile.view',
        'profile.update' => 'profile.view',
        'profile.destroy' => 'profile.view',
        'settings.building-type.index' => 'settings.building-type.view',
        'settings.building-type.create' => 'settings.building-type.view',
        'settings.building-type.store' => 'settings.building-type.view',
        'settings.building-type.edit' => 'settings.building-type.view',
        'settings.building-type.update' => 'settings.building-type.view',
        'settings.building-type.destroy' => 'settings.building-type.view',
        'settings.building-type.archive' => 'settings.building-type.view',
        'settings.building-type.restore' => 'settings.building-type.view',
        'settings.service-engaging.index' => 'settings.service-engaging.view',
        'settings.service-engaging.create' => 'settings.service-engaging.view',
        'settings.service-engaging.store' => 'settings.service-engaging.view',
        'settings.service-engaging.edit' => 'settings.service-engaging.view',
        'settings.service-engaging.update' => 'settings.service-engaging.view',
        'settings.service-engaging.destroy' => 'settings.service-engaging.view',
        'settings.service-engaging.archive' => 'settings.service-engaging.view',
        'settings.service-engaging.restore' => 'settings.service-engaging.view',
        'settings.external-wall-construction.index' => 'settings.external-wall-construction.view',
        'settings.external-wall-construction.create' => 'settings.external-wall-construction.view',
        'settings.external-wall-construction.store' => 'settings.external-wall-construction.view',
        'settings.external-wall-construction.edit' => 'settings.external-wall-construction.view',
        'settings.external-wall-construction.update' => 'settings.external-wall-construction.view',
        'settings.external-wall-construction.destroy' => 'settings.external-wall-construction.view',
        'settings.external-wall-construction.archive' => 'settings.external-wall-construction.view',
        'settings.external-wall-construction.restore' => 'settings.external-wall-construction.view',
        'settings.roof-type.index' => 'settings.roof-type.view',
        'settings.roof-type.create' => 'settings.roof-type.view',
        'settings.roof-type.store' => 'settings.roof-type.view',
        'settings.roof-type.edit' => 'settings.roof-type.view',
        'settings.roof-type.update' => 'settings.roof-type.view',
        'settings.roof-type.destroy' => 'settings.roof-type.view',
        'settings.roof-type.archive' => 'settings.roof-type.view',
        'settings.roof-type.restore' => 'settings.roof-type.view',
        'settings.scope-of-work.index' => 'settings.scope-of-work.view',
        'settings.scope-of-work.create' => 'settings.scope-of-work.view',
        'settings.scope-of-work.store' => 'settings.scope-of-work.view',
        'settings.scope-of-work.edit' => 'settings.scope-of-work.view',
        'settings.scope-of-work.update' => 'settings.scope-of-work.view',
        'settings.scope-of-work.destroy' => 'settings.scope-of-work.view',
        'settings.scope-of-work.archive' => 'settings.scope-of-work.view',
        'settings.scope-of-work.restore' => 'settings.scope-of-work.view',
        'settings.deliverables.index' => 'settings.deliverables.view',
        'settings.deliverables.create' => 'settings.deliverables.view',
        'settings.deliverables.store' => 'settings.deliverables.view',
        'settings.deliverables.edit' => 'settings.deliverables.view',
        'settings.deliverables.update' => 'settings.deliverables.view',
        'settings.deliverables.destroy' => 'settings.deliverables.view',
        'settings.deliverables.archive' => 'settings.deliverables.view',
        'settings.deliverables.restore' => 'settings.deliverables.view',
        'settings.level-of-difficulty.index' => 'settings.level-of-difficulty.view',
        'settings.level-of-difficulty.create' => 'settings.level-of-difficulty.view',
        'settings.level-of-difficulty.store' => 'settings.level-of-difficulty.view',
        'settings.level-of-difficulty.edit' => 'settings.level-of-difficulty.view',
        'settings.level-of-difficulty.update' => 'settings.level-of-difficulty.view',
        'settings.level-of-difficulty.destroy' => 'settings.level-of-difficulty.view',
        'settings.level-of-difficulty.archive' => 'settings.level-of-difficulty.view',
        'settings.level-of-difficulty.restore' => 'settings.level-of-difficulty.view',
        'settings.permissions.edit' => 'settings.permissions.manage',
        'settings.permissions.update' => 'settings.permissions.manage',
        'settings.activity-logs.index' => 'settings.activity-logs.view',
        'settings.users.index' => 'settings.user-accounts.manage',
        'settings.users.create' => 'settings.user-accounts.manage',
        'settings.users.store' => 'settings.user-accounts.manage',
        'settings.users.edit' => 'settings.user-accounts.manage',
        'settings.users.update' => 'settings.user-accounts.manage',
        'settings.users.destroy' => 'settings.user-accounts.manage',
        'settings.users.archive' => 'settings.user-accounts.manage',
        'settings.users.restore' => 'settings.user-accounts.manage',
        'settings.crm.arrival-input-files.index' => 'settings.crm.arrival-input-files.view',
        'settings.crm.arrival-input-files.create' => 'settings.crm.arrival-input-files.view',
        'settings.crm.arrival-input-files.store' => 'settings.crm.arrival-input-files.view',
        'settings.crm.arrival-input-files.edit' => 'settings.crm.arrival-input-files.view',
        'settings.crm.arrival-input-files.update' => 'settings.crm.arrival-input-files.view',
        'settings.crm.arrival-input-files.destroy' => 'settings.crm.arrival-input-files.view',
        'settings.crm.arrival-input-files.archive' => 'settings.crm.arrival-input-files.view',
        'settings.crm.arrival-input-files.restore' => 'settings.crm.arrival-input-files.view',
        'settings.crm.categories.index' => 'settings.crm.categories.view',
        'settings.crm.categories.create' => 'settings.crm.categories.view',
        'settings.crm.categories.store' => 'settings.crm.categories.view',
        'settings.crm.categories.edit' => 'settings.crm.categories.view',
        'settings.crm.categories.update' => 'settings.crm.categories.view',
        'settings.crm.categories.destroy' => 'settings.crm.categories.view',
        'settings.crm.categories.archive' => 'settings.crm.categories.view',
        'settings.crm.categories.restore' => 'settings.crm.categories.view',
    ],
];
